import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import FooterSection from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Header />

        <main>
          {children}
        </main>

        <FooterSection />
        
      </body>
    </html>
  );
}
